# Nome do Workflow
name: Deploy Markdown Documentation to GitHub Pages

# Acionadores: o workflow é executado em pushes para os ramos 'main' ou 'preview'
on:
  push:
    branches:
      - main
      - preview

# Permissões necessárias para que a Ação possa escrever no ramo gh-pages
permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      # 1. Faz o checkout do código do ramo que acionou o workflow
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Prepara os ficheiros para publicação
      # Cria um diretório temporário e copia os ficheiros .md para lá
      - name: Prepare publish directory
        run: |
          mkdir build
          cp README.md build/
          cp -r docs build/

      # 3. Implementa para PRODUÇÃO (raiz) se o ramo for 'main'
      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Publica o conteúdo do diretório que preparámos
          publish_dir: ./build
          # Ao publicar na raiz, não apague a pasta 'preview'
          clean_exclude: |
            preview

      # 4. Implementa para PRÉ-VISUALIZAÇÃO (subpasta /preview) se o ramo for 'preview'
      - name: Deploy to Preview
        if: github.ref == 'refs/heads/preview'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Publica o conteúdo do diretório que preparámos
          publish_dir: ./build
          # Coloca os ficheiros dentro da pasta 'preview' no ramo gh-pages
          destination_dir: preview
