# Nome do Workflow
name: Build and Deploy Documentation to GitHub Pages

# Acionadores: o workflow é executado em pushes para os ramos 'main' ou 'preview'
on:
  push:
    branches:
      - main
      - preview

# Permissões necessárias para que a Ação possa escrever no ramo gh-pages
permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      # 1. Faz o checkout do código do ramo que acionou o workflow
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Constrói os ficheiros HTML a partir do Markdown
      - name: Build HTML from Markdown
        run: |
          # Cria o diretório de saída
          mkdir build

          # Converte README.md para index.html (página principal)
          # A flag --standalone cria um ficheiro HTML completo
          pandoc README.md --standalone -o build/index.html

          # Cria a subpasta para os outros documentos
          mkdir build/docs

          # Converte cada ficheiro .md dentro da pasta /docs para .html
          for file in docs/*.md; do
            filename=$(basename "$file" .md)
            pandoc "$file" --standalone -o "build/docs/$filename.html"
          done
          
          # ✅ PASSO CRÍTICO: Corrige os links internos nos ficheiros HTML gerados
          # Procura todos os ficheiros .html e substitui as referências a ".md" por ".html"
          find build -type f -name "*.html" -exec sed -i 's/\.md/\.html/g' {} +

      # 3. Implementa para PRODUÇÃO (raiz) se o ramo for 'main'
      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          clean_exclude: |
            preview

      # 4. Implementa para PRÉ-VISUALIZAÇÃO (subpasta /preview) se o ramo for 'preview'
      - name: Deploy to Preview
        if: github.ref == 'refs/heads/preview'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          destination_dir: preview